version: "3"
services:
  hugegraph-server:
    image: hugegraph/hugegraph
    restart: always
    container_name: graph_server
    ports:
      - 8080:8080
  hugegraph-hubble:
    image: hugegraph/hubble
    container_name: graph_hubble
    restart: always
    privileged: true
    ports:
      - 8088:8088
  hugegraph-loader:
    image: hugegraph/loader
    container_name: graph_loader
    restart: always
    ports:
      - 18088:8088
  mysql:
    restart: always
    image: mysql:5.7
    container_name: bdtx_mysql
    volumes:
      - ./mysql_data:/mydir
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=hugegraph_db"
      - "TZ=Asia/Shanghai"
    ports:
      - 3308:3306
